### PR TITLE
chore: add KUBECONFIG

### PR DESCRIPTION
**Pull request by teleivo**

### CODE REVIEW

**Comment by teleivo** [comment]
not sure if that always make sense? I mean, is it ever just in a default place (in home) that skaffold picks it up anyway. At least when I develop using our cluster I set it to the path of the autogenerated one within our infra repo. When using kind skaffold figures it out automatically https://skaffold.dev/docs/environment/local-cluster/ so in this case I don't need to provide it.

**Comment by teleivo** [comment]
@tonsV2 I think you wanted to get @radnov opinion on this

**Comment by radnov** [comment]
> @tonsV2 I think you wanted to get @radnov opinion on this

I think it's fine having an explicit `KUBECONFIG` var in the example. `skaffold` and `kubectl` do pickup a bunch of "default" use-cases, but someone might have a different setup.

**Comment by teleivo** [comment]
> > @tonsV2 I think you wanted to get @radnov opinion on this
> 
> I think it's fine having an explicit `KUBECONFIG` var in the example. `skaffold` and `kubectl` do pickup a bunch of "default" use-cases, but someone might have a different setup.

where do you put your kubeconfig for it to "just" work? If you have a suggestion I'll move my file. I just don't want to do the export KUBECONFIG all the time

**Comment by radnov** [comment]
> where do you put your kubeconfig for it to "just" work? If you have a suggestion I'll move my file. I just don't want to do the export KUBECONFIG all the time

Sorry. my comment was a bit misleading, to be honest. Currently I either set `KUBECONFIG` to the relevant file created in the infra project or do `aws eks update-kubeconfig --name instance-cluster-test` to get the latest kubeconfig into the default `~/.kube/config` file.

**Comment by tonsV2** [comment]
Sorry for the lack of attention here. Let's have a chat about this during our Friday gathering :-)

**Comment by teleivo** [comment]
Closing this for now as I don't think we agree on it and its taking up place in my todo list. Reopening is always possible 😋

**Pull request closed without merging**
